services:
  s4c-trajectory-app:
    build: .
    ports:
      - "3000:3000"
    restart: always
    container_name: s4c-trajectory-monitoring
    volumes:
      - ./CHAN_S4C_last15min.csv:/app/CHAN_S4C_last15min.csv:ro
      - ./CHMA_S4C_last15min.csv:/app/CHMA_S4C_last15min.csv:ro
      - ./DPT9_S4C_last15min.csv:/app/DPT9_S4C_last15min.csv:ro
      - ./NKSW_S4C_last15min.csv:/app/NKSW_S4C_last15min.csv:ro
      - ./PJRK_S4C_last15min.csv:/app/PJRK_S4C_last15min.csv:ro
      - ./SISK_S4C_last15min.csv:/app/SISK_S4C_last15min.csv:ro
      - ./SOKA_S4C_last15min.csv:/app/SOKA_S4C_last15min.csv:ro
      - ./SRTN_S4C_last15min.csv:/app/SRTN_S4C_last15min.csv:ro
      - ./TP00_S4C_last15min.csv:/app/TP00_S4C_last15min.csv:ro
      - ./UDON_S4C_last15min.csv:/app/UDON_S4C_last15min.csv:ro
      - ./UTTD_S4C_last15min.csv:/app/UTTD_S4C_last15min.csv:ro